document.write( '<marquee>Buy 19th Edition Inamdar book from amazon</marquee>\n' );
document.write( '<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n' );
document.write( '<style>\n' );
document.write( '.marginauto {\n' );
document.write( '    margin: 0px auto 0px;\n' );
document.write( '    display: block;\n' );
document.write( '}\n' );
document.write( '</style>\n' );
document.write( '<a href=\"https://amzn.to/2UBU9ax\">\n' );
document.write( '<br><img src=\"https://1.bp.blogspot.com/-GlvVZ7eHxHc/YPnO1veWr4I/AAAAAAAAIIU/E4C5fB-gvcEMMA3jTIt3DjPBtBam9faeQCNcBGAsYHQ/s320/ezgif-4-e7950cc1a230%2B%25281%2529.gif\" class=\"marginauto\" width=\"400\"height=\"170\"></a>\n' );
