document.write( '<marquee>This test is sponsored by:- Online Guru</marquee>\n' );
document.write( '<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n' );
document.write( '<style>\n' );
document.write( '.marginauto {\n' );
document.write( '    margin: 0px auto 0px;\n' );
document.write( '    display: block;\n' );
document.write( '}\n' );
document.write( '</style>\n' );
document.write( '<a href=\"https://youtu.be/WamJ8Cu6uDE\">\n' );
document.write( '<br><img src=\"https://s6.gifyu.com/images/VID-20210715-WA00111.gif\" class=\"marginauto\" width=\"400\"height=\"170\"></a>\n' );